### ISSUE TITLE
"no valid decryption key supplied" error when trying to decrypt cipher

### ISSUE THREAD

**Issue by shahzaib-sheikh** [S2-/sshenc.sh#3]
using 2048 key pair.

**Comment by shahzaib-sheikh** [comment]
issue was multiline encrypted data, more information @ https://stackoverflow.com/questions/35289912/openssl-enc-base64-d-does-not-decode-strings-after-a-certain-length
Created a pull request #4 to fix this issue
Please review thanks

**Comment by 5im-0n** [comment]
merged f4127b7282e3b8d3a83166ee4c1c09478ffef545
