### ISSUE TITLE
Retain pre-openssl1.1.1 tests for legacy users

### ISSUE THREAD

**Issue by shahzaib-sheikh** [S2-/sshenc.sh#5]
Can we retain (re-add) `tests.sh` with different name like `tests-pre1.1.1.sh` for `sshenc-pre1.1.1.sh`. It would be helpful for people who are not able to get openssl1.1.1 on their machine. Glad to see the changes, but somehow I'm not able to run the new version on my machine `openssl version -a` returns this 
`LibreSSL 2.8.3`
`built on: date not available`
`platform: information not available`
`options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)` 
`compiler: information not available`
`OPENSSLDIR: "/private/etc/ssl"`

could you advise what steps are needed to be able to run the 1.1.1 compatible changes.
Thanks.

**Comment by 5im-0n** [comment]
Added a configuration to `test.sh`: https://github.com/S2-/sshenc.sh/commit/c3ebbbfa06e68ef1d58d1332b48189d9347911cb#diff-63ab6decfd52638355f6a527c3c6dee2R3
Would this work?

I don't know how you can use OpenSSL 1.1.1, it depends on your system. Does LibreSSL have the `-iter` and `-pbkdf2` parameters?

It seems like the version of LibreSSL that introduced the new parameters is [2.9.1](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.1-relnotes.txt)

**Comment by shahzaib-sheikh** [comment]
Yeah! perfect. 
I'm using mac.  No I think it doesn't support `-pbkdf` or `-iter` parameters. Yeah I'll try upgrading it. 
Closing this issue.
Thanks.
