### ISSUE TITLE
do you think it is safe to store keys in temp files in /tmp ?

### ISSUE THREAD

**Issue by cypa** [S2-/sshenc.sh#6]
I'd prefer
`temp_dir="$(mktemp --tmpdir=~/.sshenc/tmp -d -t "$me.XXXXXX")"`

**Comment by 5im-0n** [comment]
Well the temp dir is `-rw-------` on your user, so it's as safe as your home dir, but pull requests welcome!

**Comment by 5im-0n** [comment]
You can `export TMPDIR=~/.sshenc/tmp` before running the script to change the temp dir.
